[package]
name = "flip"
version = "0.1.0"
authors = ["panstromek <panstromek@seznam.cz>"]
edition = "2024"

[lib]
name = "flip"
path = "lib.rs"

[dependencies]
engine-traits = { path = "../engine-traits" }
